"""empty message

Revision ID: 15098bfbe765
Revises: b6014173fce3
Create Date: 2022-03-27 11:45:25.891442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15098bfbe765'
down_revision = 'b6014173fce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('product_cost', sa.Float(precision=2), nullable=False),
    sa.Column('amount_in_inventory', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    # ### end Alembic commands ###
