"""empty message

Revision ID: 697d16a95bda
Revises: 15098bfbe765
Create Date: 2022-03-28 14:14:47.886551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697d16a95bda'
down_revision = '15098bfbe765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventory_name_key', 'inventory', type_='unique')
    op.drop_constraint('products_name_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_name_key', 'products', ['name'])
    op.create_unique_constraint('inventory_name_key', 'inventory', ['name'])
    # ### end Alembic commands ###
