"""empty message

Revision ID: ab6b32365862
Revises: 4cc38e5d10bb
Create Date: 2022-03-28 15:49:43.337686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6b32365862'
down_revision = '4cc38e5d10bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('image', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
