"""empty message

Revision ID: b6014173fce3
Revises: 82d7cdd0fba6
Create Date: 2022-03-27 11:38:30.461361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6014173fce3'
down_revision = '82d7cdd0fba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('product_cost', sa.Float(precision=2), nullable=False),
    sa.Column('order_date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
