"""empty message

Revision ID: d7c841d8f046
Revises: b869be6a6c42
Create Date: 2022-04-14 10:24:56.715094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c841d8f046'
down_revision = 'b869be6a6c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['customer.id'], )
    )
    op.add_column('customer', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('post', sa.Column('customer_id', sa.String(), nullable=True))
    op.drop_constraint('post_user_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'customer', ['customer_id'], ['id'])
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_user_id_fkey', 'post', 'customer', ['user_id'], ['username'])
    op.drop_column('post', 'customer_id')
    op.drop_column('customer', 'bio')
    op.drop_table('followers')
    # ### end Alembic commands ###
